name: Release Simple

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '0.1.7'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and upload
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: jgf
          target: x86_64-unknown-linux-gnu,x86_64-apple-darwin,aarch64-apple-darwin,x86_64-pc-windows-msvc
          token: ${{ secrets.GITHUB_TOKEN }}
          archive: $bin-$target