name: Release JGF Simple

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - npm/jgf/package.json

jobs:
  check:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.version.outputs.changed }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Check version changes
        uses: EndBug/version-check@v2
        id: version
        with:
          static-checking: localIsNew
          file-url: https://unpkg.com/jgf@latest/package.json
          file-name: npm/jgf/package.json

  # 일단 macOS ARM만 테스트
  build-macos:
    needs: check
    if: needs.check.outputs.version_changed == 'true'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
          
      - name: Build for macOS ARM64
        run: cargo build --release --target aarch64-apple-darwin
        
      - name: Rename binary
        run: |
          mv target/aarch64-apple-darwin/release/jgf jgf-darwin-arm64
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jgf-darwin-arm64
          path: jgf-darwin-arm64

  # 테스트용 간단한 publish
  test-publish:
    needs: [check, build-macos]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: jgf-darwin-arm64
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Create simple package structure
        run: |
          mkdir -p npm/jgf-darwin-arm64
          cp jgf-darwin-arm64 npm/jgf-darwin-arm64/jgf
          chmod +x npm/jgf-darwin-arm64/jgf
          echo '{"name":"@jgf/darwin-arm64","version":"${{ needs.check.outputs.version }}","os":["darwin"],"cpu":["arm64"]}' > npm/jgf-darwin-arm64/package.json
          
      - name: Test package creation
        run: |
          echo "Package created successfully"
          ls -la npm/jgf-darwin-arm64/